image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11

variables:
  CI_DEBUG_SERVICES: "false"

stages:
  - test
  - build
  - publish

test:pylint-pytest:
  stage: test
  tags:
    - linux-docker-x64-hetzner
  image: docker
  before_script:
    - TXT_HEAD="\e[46m\e[1;37m" && TXT_ERROR="\e[1;31m" && TXT_CLEAR="\e[0m"
    #- COMPOSE_FILE=docker/opsiconfd-dev/docker-compose.yml
    - COMPOSE_PROJECT_NAME=opsiconfd-test-$CI_JOB_ID
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227
    - CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
    - export LOCAL_WORKSPACE_DIR=$(docker inspect $CONTAINER_ID -f "{{ range .Mounts }}{{ if eq .Destination \"/builds\" }}{{ .Source }}{{end}}{{end}}")/uib/opsiconfd/

    - cp docker/opsiconfd-dev/common.env docker/opsiconfd-dev/.env
    - env | grep "OPSILICSRV_TOKEN=" >> docker/opsiconfd-dev/.env
    - echo "LOCAL_WORKSPACE_DIR=../.." >> docker/opsiconfd-dev/.env
    - echo "OPSISERVER_DEV_OPSICONFD_FORWARD_PORT=" >> docker/opsiconfd-dev/.env
    - echo "OPSISERVER_CS_OPSICONFD_FORWARD_PORT=" >> docker/opsiconfd-dev/.env
    - echo "DEV_USER=" >> docker/opsiconfd-dev/.env
    - echo "DEV_UID=" >> docker/opsiconfd-dev/.env

    - echo -e "${TXT_HEAD}Build docker images${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml build

  after_script:
    # Unfortunatly after_script is currently not executed when a job is canceled
    # https://gitlab.com/groups/gitlab-org/-/epics/10158
    - TXT_HEAD="\e[46m\e[1;37m" && TXT_ERROR="\e[1;31m" && TXT_CLEAR="\e[0m"
    #- COMPOSE_FILE=docker/opsiconfd-dev/docker-compose.yml
    - COMPOSE_PROJECT_NAME=opsiconfd-test-$CI_JOB_ID
    - '[ "$CI_DEBUG_SERVICES" = "true" ] && docker compose -f docker/opsiconfd-dev/docker-compose.yml logs'
    - echo -e "${TXT_HEAD}Stop docker containers${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml down -v
  script:
    - echo -e "${TXT_HEAD}Prepare docker containers${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml up --detach --wait --wait-timeout 30
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml logs opsiserver43-dev

    - echo -e "${TXT_HEAD}Run linters${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run pylint opsiconfd tests
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run ruff opsiconfd tests
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run mypy opsiconfd tests

    - echo -e "${TXT_HEAD}Run pytest${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests

    - echo -e "${TXT_HEAD}Run perftests${TXT_CLEAR}"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run opsiconfd -c tests/data/default-opsiconfd.conf --workers=1 --log-level-file=5 --log-file=opsiconfd-perftest.log --max-session-per-ip=20000 &
    - sleep 10

    - echo -e "${TXT_HEAD}Run opsiconfd-perftest${TXT_CLEAR}"
    # Average request time has to be faster than 10 ms
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_session_loading.json --max-errors 0 --max-avg-seconds-per-request 0.01 || (
        echo -e "${TXT_ERROR}opsiconfd-perftest.py failed${TXT_CLEAR}"
        cat opsiconfd-perftest.log
        exit 1
      )

    - echo -e "${TXT_HEAD}Run opsiconfd-backend-perftest${TXT_CLEAR}"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run ./perftest/opsiconfd-backend-perftest.py --products 100 --clients 100 --iterations 5 --max-real 30000 || (
        echo -e "${TXT_ERROR}opsiconfd-backend-perftest.py failed${TXT_CLEAR}"
        cat opsiconfd-perftest.log
        exit 1
      )

    - echo -e "${TXT_HEAD}Run file-download memory test${TXT_CLEAR}"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run python ./perftest/file-download.py --clients=5 --file-size=500 --min-download-time=20 --memory-usage-limit 20 || (
        echo -e "${TXT_ERROR}file-download.py failed${TXT_CLEAR}"
        cat opsiconfd-perftest.log
        exit 1
      )
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run python ./perftest/file-download.py --clients=10 --file-size=200 --min-download-time=20 --memory-usage-limit 20 --range-requests || (
        echo -e "${TXT_ERROR}file-download.py failed (range-requests)${TXT_CLEAR}"
        cat opsiconfd-perftest.log
        exit 1
      )

    - echo -e "${TXT_HEAD}Run messagebus websocket load test${TXT_CLEAR}"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiserver43-dev poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
        echo -e "${TXT_ERROR}messagebus-clients.py failed (range-requests)${TXT_CLEAR}"
        cat opsiconfd-perftest.log
        exit 1
      )
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: 'opsiconfd_test'
    paths:
      - coverage.xml
    expire_in: 3 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:linux-pyinstaller:
  stage: build
  tags:
    - linux-docker-x64-hetzner
  script:
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - opsi-dev-cli self upgrade
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l debug pyinstaller build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-amd64
    # Check if binary is working
    - ./opsiconfd-amd64/opsiconfd -c opsiconfd_data/etc/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-linux-pyinstaller'
    paths:
      - opsiconfd-amd64
    expire_in: 2 day

build:arm64-pyinstaller:
  stage: build
  tags:
    - arm64
  script:
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - opsi-dev-cli self upgrade
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l debug pyinstaller build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local ./opsiconfd-arm64/opsiconfd -c opsiconfd_data/etc/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-arm64-pyinstaller'
    paths:
      - opsiconfd-arm64
    expire_in: 2 day


#publish:obs_int:
#  stage: publish
#  dependencies:
#    - build:linux-pyinstaller
#    - build:arm64-pyinstaller
#  script:
#    - *install_tools
#    - opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.3:development
#  only:
#    - tags

publish:obs_ext:
  stage: publish
  tags:
    - linux-docker-x64-hetzner
  dependencies:
    - build:linux-pyinstaller
    - build:arm64-pyinstaller
  script:
    - opsi-dev-cli self upgrade
    - opsi-dev-cli -l info packaging obs update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
    - opsi-dev-cli -l info changelog from-git output
    - opsi-dev-cli release-service register-package-version opsiconfd SERVER_PACKAGE --changelog-file output/changelog.md
    - opsi-dev-cli release-service push-repository-state opsiconfd SERVER_PACKAGE SERVER_PACKAGE-4.3-development
  only:
    - tags
