image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.10

stages:
  - test
  - build
  - publish

.install_tools: &install_tools |
  export DEBIAN_FRONTEND=noninteractive
  apt update
  apt -y install debhelper osc tar wget
  if [ "$(dpkg --print-architecture)" = "amd64" ]; then
    wget "$OPSIDEVTOOLS_URL_LINUX_X64" -O opsi-dev-tools.tar.gz
  else
    wget "$OPSIDEVTOOLS_URL_LINUX_ARM64" -O opsi-dev-tools.tar.gz
  fi
  tar -xvf opsi-dev-tools.tar.gz

.prepare_tests: &prepare_tests |
  # Install debian packages
  export DEBIAN_FRONTEND=noninteractive
  apt update
  apt -y install mariadb-client bc

  # Grant full database access to opsi user
  mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON opsitest.* TO 'opsi'@'%';"

  # Get config files from opsi-server package
  [ -e /etc/opsi ] && rm -r /etc/opsi
  [ -e ../opsi-server ] && rm -r ../opsi-server
  url=$(git remote -v | grep fetch | cut -f2 | sed s'#/opsiconfd.git.*#/opsi-server.git#')
  #branch=$(git rev-parse --abbrev-ref HEAD)
  branch=master
  GIT_TERMINAL_PROMPT=0 git clone --branch $branch $url ../opsi-server
  cp -a ../opsi-server/opsi-server_data/etc /etc/opsi

  # Configure opsiconfd
  mkdir -p /var/lib/opsi/repository /var/lib/opsi/depot

  echo "redis-internal-url = redis://redis" >> tests/data/default-opsiconfd.conf
  echo "log-level-stderr = 0" >> tests/data/default-opsiconfd.conf
  echo "log-level-file = 6" >> tests/data/default-opsiconfd.conf
  echo "log-file = /tmp/opsiconfd.log" >> tests/data/default-opsiconfd.conf

  # Installing opsi test modules file
  [ -z "${OPSILICSRV_TOKEN}" ] && (echo "OPSILICSRV_TOKEN not set" 1>&2 ; exit 1)
  mkdir -p /etc/opsi/licenses
  wget --header="Authorization: Bearer ${OPSILICSRV_TOKEN}" "https://opsi-license-server.uib.gmbh/api/v1/licenses/test?usage=opsiconfd-gitlab-ci" -O /etc/opsi/licenses/test.opsilic

  # Create dirs
  mkdir -p /var/log/opsi/clientconnect
  mkdir -p /var/lib/opsi/public
  mkdir -p /tftpboot

  # Install poetry
  pip3 install poetry
  poetry config experimental.new-installer false
  poetry lock --no-update
  poetry install
  poetry run opsiconfd -c tests/data/default-opsiconfd.conf -l5 setup

  # Create adminuser used in tests
  useradd adminuser
  echo "adminuser:adminuser" | chpasswd
  adduser adminuser opsiadmin
  adduser adminuser opsifileadmins

.perftest: &perftest |
  export OPSICONFD_MAX_SESSIONS_PER_IP=20000
  poetry run opsiconfd -c tests/data/default-opsiconfd.conf &
  sleep 10
  echo "---------------------------------------"
  echo "Run perftest"
  echo "---------------------------------------"
  poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_session_loading.json -w /tmp/perftest-result
  [ $(grep errors= /tmp/perftest-result | cut -d '=' -f2) -gt 0 ] && ( cat /tmp/perftest-result; echo 'Errors in perftest' >&2; exit 1 )
  # Average request time has to be faster than 10 ms
  echo "$(grep avg_seconds_per_request= /tmp/perftest-result | cut -d '=' -f2)<0.01" | bc > /tmp/bc-result
  [ $(cat /tmp/bc-result) = "1" ] || ( cat /tmp/perftest-result; echo 'Average seconds per request >= 10 ms' >&2; exit 1 )

.pytest: &pytest |
  [ -e /tmp/opsiconfd.log ] && rm /tmp/opsiconfd.log
  poetry run opsiconfd -c tests/data/default-opsiconfd.conf  &
  sleep 10
  echo "---------------------------------------"
  echo "Run tests"
  echo "---------------------------------------"
  exit_code=0
  poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests --ignore=tests/test_config.py || exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "---------------------------------------"
    echo "opsiconfd log"
    echo "---------------------------------------"
    cat /tmp/opsiconfd.log
    exit $exit_code
  fi
  poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests/test_config.py

.pylint: &pylint |
  echo "---------------------------------------"
  echo "Run pylint"
  echo "---------------------------------------"
  poetry run pylint --disable=R,fixme opsiconfd tests
  poetry run flake8 opsiconfd tests

test:perftest:
  services:
    - name: mysql:latest
      command:
        - --max_connections=1000
        - --default-authentication-plugin=mysql_native_password
    - name: redislabs/redistimeseries:latest
      alias: redis
  variables:
    MYSQL_ROOT_PASSWORD: "opsi"
    MYSQL_DATABASE: "opsitest"
    MYSQL_USER: "opsi"
    MYSQL_PASSWORD: "opsi"
  stage: test
  script:
    - *prepare_tests
    - *perftest

test:pylint-pytest:
  services:
    - name: mysql:latest
      command:
        - --max_connections=1000
        - --default-authentication-plugin=mysql_native_password
    - name: redislabs/redistimeseries:latest
      alias: redis
  variables:
    MYSQL_ROOT_PASSWORD: "opsi"
    MYSQL_DATABASE: "opsitest"
    MYSQL_USER: "opsi"
    MYSQL_PASSWORD: "opsi"
  stage: test
  script:
    - *prepare_tests
    - *pylint
    - *pytest
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: 'opsiconfd_test'
    paths:
      - coverage.xml
    expire_in: 3 days
    reports:
      cobertura: coverage.xml

build:linux-pyinstaller:
  stage: build
  script:
    - *install_tools
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-tool -l debug --pyinstaller-poetry-build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-amd64
    # Check if binary is working
    - ./opsiconfd-amd64/opsiconfd -c opsiconfd_data/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-linux-pyinstaller'
    paths:
      - opsiconfd-amd64
    expire_in: 2 day

build:arm64-pyinstaller:
  stage: build
  tags:
    - arm64
  script:
    - *install_tools
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-tool -l debug --pyinstaller-poetry-build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local ./opsiconfd-arm64/opsiconfd -c opsiconfd_data/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-arm64-pyinstaller'
    paths:
      - opsiconfd-arm64
    expire_in: 2 day


publish:obs_int:
  stage: publish
  dependencies:
    - build:linux-pyinstaller
    - build:arm64-pyinstaller
  script:
    - *install_tools
    - ./opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:development
  only:
    - tags

publish:obs_ext:
  stage: publish
  dependencies:
    - build:linux-pyinstaller
    - build:arm64-pyinstaller
  script:
    - *install_tools
    - ./opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:development
  only:
    - tags
