image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11

variables:
  CI_DEBUG_SERVICES: "false"

stages:
  - test
  - build
  - publish

before_script:
  # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227
  - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
  - export LOCAL_WORKSPACE_DIR=$(docker inspect $CONTAINER_ID -f "{{ range .Mounts }}{{ if eq .Destination \"/builds\" }}{{ .Source }}{{end}}{{end}}")/uib/opsiconfd/
  - docker compose -f docker/opsiconfd-dev/docker-compose.yml build

after_script:
  - '[ "$CI_DEBUG_SERVICES" = "true" ] && docker compose -f docker/opsiconfd-dev/docker-compose.yml logs'
  - docker compose -f docker/opsiconfd-dev/docker-compose.yml down -v

test:pylint-pytest:
  stage: test
  tags:
    - linux-docker-x64-hetzner
  image: docker
  services:
  script:
    - apt-get update
    - apt-get install --yes bc

    - env | grep "OPSILICSRV_TOKEN=" > docker/opsiconfd-dev/local.env
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml up --detach --wait --wait-timeout 30
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry lock --no-update
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry install

    - echo "Run linters"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run pylint --disable=R,fixme,E0012 opsiconfd tests
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ruff opsiconfd tests
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run mypy opsiconfd tests

    - echo "Run pytest"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests

    - echo "Run perftests"
    #- docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run opsiconfd -c tests/data/default-opsiconfd.conf -l6 setup
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run opsiconfd -c tests/data/default-opsiconfd.conf --workers=1 --log-level-file=5 --log-file=opsiconfd-perftest.log --max-session-per-ip=20000 &
    - sleep 10

    - echo "Run opsiconfd-perftest"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_session_loading.json -w perftest-result
    - cat perftest-result
    - |
      [ $(grep errors= perftest-result | cut -d '=' -f2) -gt 0 ] && (
        echo "Errors in perftest" >&2
        exit 1
      )
    # Average request time has to be faster than 10 ms
    - echo "$(grep avg_seconds_per_request= perftest-result | cut -d '=' -f2)<0.01" | bc > bc-result
    - |
      [ $(cat bc-result) = "1" ] || (
        echo "Average seconds per request >= 10 ms" >&2
        exit 1
      )

    - echo "Run opsiconfd-backend-perftest"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/opsiconfd-backend-perftest.py --products 100 --clients 100 --iterations 5 > perftest-result || (
        echo "opsiconfd-backend-perftest.py failed" >&2
        cat perftest-result
        cat opsiconfd-perftest.log
        exit 1
      )
    - cat perftest-result
    - echo "$(grep real= perftest-result | cut -d '=' -f2)<30000" | bc > /tmp/bc-result
    - |
      [ $(cat /tmp/bc-result) = "1" ] || (
        echo "Required time >= 30 s" >&2
        exit 1
      )

    - echo "Run file-download memory test"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run python ./perftest/file-download.py --clients=5 --file-size=500 --min-download-time=20 --memory-usage-limit 20 || (
        echo "file-download.py failed" >&2
        cat opsiconfd-perftest.log
        exit 1
      )
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run python ./perftest/file-download.py --clients=10 --file-size=200 --min-download-time=20 --memory-usage-limit 20 --range-requests || (
        echo "file-download.py failed (range-requests)" >&2
        cat opsiconfd-perftest.log
        exit 1
      )

    - echo "Run messagebus websocket load test"
    - |
      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
        echo "messagebus-clients.py failed" >&2
        cat opsiconfd-perftest.log
        exit 1
      )

    - echo "Stop docker containers"
    - docker compose -f docker/opsiconfd-dev/docker-compose.yml down -v
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: 'opsiconfd_test'
    paths:
      - coverage.xml
    expire_in: 3 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:linux-pyinstaller:
  stage: build
  tags:
    - linux-docker-x64-hetzner
  script:
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - opsi-dev-cli self update
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l debug pyinstaller build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-amd64
    # Check if binary is working
    - ./opsiconfd-amd64/opsiconfd -c opsiconfd_data/etc/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-linux-pyinstaller'
    paths:
      - opsiconfd-amd64
    expire_in: 2 day

build:arm64-pyinstaller:
  stage: build
  tags:
    - arm64
  script:
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - opsi-dev-cli self update
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l debug pyinstaller build
    - mv opsiconfd opsiconfd.src
    - mv dist/opsiconfd ./opsiconfd-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local ./opsiconfd-arm64/opsiconfd -c opsiconfd_data/etc/opsiconfd.conf --version
  artifacts:
    name: 'opsiconfd-arm64-pyinstaller'
    paths:
      - opsiconfd-arm64
    expire_in: 2 day


#publish:obs_int:
#  stage: publish
#  dependencies:
#    - build:linux-pyinstaller
#    - build:arm64-pyinstaller
#  script:
#    - *install_tools
#    - opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.3:development
#  only:
#    - tags

publish:obs_ext:
  stage: publish
  tags:
    - linux-docker-x64-hetzner
  dependencies:
    - build:linux-pyinstaller
    - build:arm64-pyinstaller
  script:
    - opsi-dev-cli self update
    - opsi-dev-cli -l info packaging obs update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
    - opsi-dev-cli -l info changelog from-git output
    - opsi-dev-cli release-service register-package-version opsiconfd SERVER_PACKAGE --changelog-file output/changelog.md
    - opsi-dev-cli release-service push-repository-state opsiconfd SERVER_PACKAGE SERVER_PACKAGE-4.3-development
  only:
    - tags
