[tool.poetry]
name = "opsiconfd"
version = "4.2.0.134"
description = "opsi configuration service"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
include = [
    "run-opsiconfd",
    "opsiconfd_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
# We need python 3.7 for contextvars in combination with asyncio
python = "^3.7"
# Get the latest python-opsi from branch 4.2
#python-opsi = { git = "git@gitlab.uib.local:uib/python-opsi.git", branch = "v4.2" }
#python-opsi = {path = "python-opsi"}
python-opsi = "^4.2.0.80"
gunicorn = "^20.0.4"
uvicorn = "^0.13.3"
fastapi = "^0.52.0"
orjson = "^2.5.1"
itsdangerous = "^1.1.0"
msgpack = "^1.0.0"
redis = "^3.4.1"
colorlog = "^4.1.0"
aiofiles = "^0.4.0"
configargparse = "^1.0"
yappi = "^1.2.3"
aiologger = "^0.5.0"
aredis = "^1.1.8"
psutil = "^5.7.0"
aiohttp = "^3.6.2"
dnspython = "^1.16.0"
python-magic = "^0.4.15"
mysqlclient = "^1.4.6"
distro = "^1.5.0"
ldap3 = "^2.8.1"
lz4 = "^3.1.0"
wsgidav = "^3.0.3"
aiozeroconf = "^0.1.8"
uvloop = "^0.14.0"
websockets = "^8.1"
pympler = "^0.9"
guppy3 = "^3.1.0"
objgraph = "^3.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
idna = "^2.9"
pylint = "^2.4.4"
opsi-dev-tools = "^1.0.4"
pytest-cov = "^2.10.0"
pytest-asyncio = "^0.14.0"
pyinstaller = "^4.0"
mock = "^4.0.3"

[tool.poetry.scripts]
opsiconfd = "opsiconfd.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

