version: '3.3'

services:
  opsiconfd42:
    depends_on:
      - mysql
      - redis
    build:
      context: ..
      dockerfile: docker/opsiconfd-dev-Dockerfile
    ports:
      - "44472:4447"
    volumes:
      - ..:/src
    environment:
      OPSICONFD_EXTERNAL_URL: https://localhost:4447
      OPSICONFD_INTERNAL_URL: https://opsiconfd42:4447
      OPSICONFD_GRAFANA_INTERNAL_URL: http://adminuser:adminuser@grafana:3000
      OPSICONFD_GRAFANA_EXTERNAL_URL: http://localhost:3000
      OPSICONFD_MAX_SESSIONS_PER_IP: 0
      OPSICONFD_WORKERS: 1
      OPSICONFD_LOG_LEVEL_STDERR: 4
    #restart: always
    working_dir: /poetry
    entrypoint: ["poetry", "run", "opsiconfd"]
    #entrypoint: ["sleep", "infinity"] 

  mysql:
    image: mysql:8
    command: --max_allowed_packet=256M --sort_buffer_size=4M
    environment:
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi

  redis:
    image: redislabs/redistimeseries:1.4.1

  opsiconfd41:
    depends_on:
      - mysql
    build:
      context: ..
      dockerfile: docker/opsiconfd41-Dockerfile
    ports:
      - "44471:4447"
    #restart: always
    #entrypoint: ["sleep", "infinity"]
    entrypoint: ["/usr/bin/opsiconfd"]
