version: '3.3'

services:
  opsiconfd-dev-43:
    hostname: ${OPSI_HOSTNAME}
    env_file:
      ../.env
    # Needed for mount
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - SYS_PTRACE
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        - USER
        - UID
    volumes:
      - ..:/workspace:cached
    ports:
      - 4448:4447
      - 3001:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: adminuser
      GF_SECURITY_ADMIN_PASSWORD: adminuser
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi
      MYSQL_HOST: localhost
      OPSICONFD_EXTERNAL_URL: https://localhost:4448
      OPSICONFD_INTERNAL_URL: https://opsiconfd-dev-43:4447
      OPSICONFD_STATIC_DIR: /workspace/opsiconfd_data/static
      # OPSICONFD_GRAFANA_INTERNAL_URL: http://adminuser:adminuser@localhost:3000
      # OPSICONFD_GRAFANA_EXTERNAL_URL: "http://localhost:3000"
    entrypoint: ["/opsiconfd-dev-entrypoint.sh"]
  configserver-dev-43:
    hostname: configserver.opsi.dev
    env_file:
      ../.env
    # Needed for mount
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - SYS_PTRACE
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        - USER
        - UID
    volumes:
      - ..:/workspace:cached
    ports:
      - 44481:4447
    environment:
      OPSI_HOSTNAME: configserver.opsi.dev
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: adminuser
      GF_SECURITY_ADMIN_PASSWORD: adminuser
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi
      MYSQL_HOST: localhost
      OPSICONFD_EXTERNAL_URL: https://localhost:44481
      OPSICONFD_INTERNAL_URL: https://configserver-dev-43:4447
      OPSICONFD_STATIC_DIR: /workspace/opsiconfd_data/static
    entrypoint: ["/configserver-dev-entrypoint.sh"]
