version: '3.3'

networks:
  opsiconfd_internal:
    internal: true
  opsiconfd_external:
    external: true

services:
  opsiconfd:
    depends_on:
      - mysql
      - redis
      - grafana
    build:
      context: ..
      dockerfile: docker/opsiconfd-dev-Dockerfile
    volumes:
      - ..:/src
    #entrypoint: ["sleep", "infinity"]
    restart: always
    working_dir: /poetry
    entrypoint: ["poetry", "run", "opsiconfd"]
    environment:
      OPSICONFD_SSL_SERVER_KEY: ""
      OPSICONFD_WORKERS: 4
    networks:
      - opsiconfd_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opsiconfd.rule=Host(`opsiconfd.localhost`)"
      - "traefik.http.routers.opsiconfd.entrypoints=opsiconfd"
      - "traefik.http.services.opsiconfd.loadbalancer.server.port=4447"
      - "traefik.http.routers.opsiconfd.service=opsiconfd"
      #- "traefik.docker.network=docker_opsiconfd_internal"
      #- "traefik.port=4447"
 
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856 # Set max_allowed_packet to 256M
    #ports:
    #  - "3307:3306"
    networks:
      - opsiconfd_internal
    environment:
       MYSQL_ROOT_PASSWORD: opsi
       MYSQL_DATABASE: opsi
       MYSQL_USER: opsi
       MYSQL_PASSWORD: opsi

  redis:
    image: redislabs/redistimeseries:1.2.5
    #ports:
    #  - "6380:6379"
    networks:
      - opsiconfd_internal

  grafana:
    image: grafana/grafana:6.7.1
    environment:
      # Installing plugins needs an internet connection
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: adminuser
      GF_SECURITY_ADMIN_PASSWORD: adminuser
    ports:
      - "3000:3000"
    networks:
      - opsiconfd_internal
      - opsiconfd_external

  traefik:
    image: traefik:v2.2.0
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #- "--providers.docker.network=docker_opsiconfd_internal"
      - "--providers.docker.network=opsiconfd_internal"
      - "--entrypoints.opsiconfd.address=:4447"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "4447:4447"
      - "8080:8080"
    networks:
      - opsiconfd_internal
      - opsiconfd_external
